try:
    n = 3/0

except:
    print('Houve um erro com a divisão')
finally:
    print('até mais!')
